use tagger::tags;


pub fn parse_tag<'a>(input: &'a str) -> tags::TagPair<'a, BrownTag> {
    // Split the input string
    let mut parts = input.split("/");

    // Get the word
    let new_word = parts.next().unwrap();

    let new_tag = match parts.next().unwrap() {
        "." => BrownTag::SentenceCloser,
        "(" => BrownTag::LeftParen,
        ")" => BrownTag::RightParen,
        "*" => BrownTag::Not,
        "--" => BrownTag::Dash,
        "," => BrownTag::Comma,
        ":" => BrownTag::Colon,
        "abl" => BrownTag::PreQualifier,
        "abn" => BrownTag::PreQuantifierN,
        "abx" => BrownTag::PreQuantifierX,
        "ap" => BrownTag::PostDeterminer,
        "at" => BrownTag::Article,
        "be" => BrownTag::Be,
        "bed" => BrownTag::Were,
        "bedz" => BrownTag::Was,
        "beg" => BrownTag::Being,
        "bem" => BrownTag::Am,
        "ben" => BrownTag::Been,
        "ber" => BrownTag::Are,
        "bez" => BrownTag::Is,
        "cc" => BrownTag::CoordinatingConjunction,
        "cd" => BrownTag::CardinalNumeral,
        "cs" => BrownTag::SubordinatingConjunction,
        "do" => BrownTag::Do,
        "dod" => BrownTag::Did,
        "doz" => BrownTag::Does,
        "dt" => BrownTag::SingularDeterminer,
        "dti" => BrownTag::DeterminerQualifier,
        "dts" => BrownTag::PluralDeterminer,
        "dtx" => BrownTag::DoubleConjunction,
        "ex" => BrownTag::Existential,
        "fw" => BrownTag::ForeignWord,
        "hl" => BrownTag::WordInHeadline,
        "hv" => BrownTag::Have,
        "hvd" => BrownTag::HadPast,
        "hvg" => BrownTag::Having,
        "hvn" => BrownTag::HadPastParticiple,
        "hvz" => BrownTag::Has,
        "in" => BrownTag::Preposition,
        "jj" => BrownTag::Adjective,
        "jjr" => BrownTag::ComparativeAdjective,
        "jjs" => BrownTag::SemSuperlativeAdjective,
        "jjt" => BrownTag::MorphSuperlativeAdjective,
        "md" => BrownTag::ModalAuxiliary,
        "nc" => BrownTag::Cited,
        "nn" => BrownTag::Noun,
        "nn$" => BrownTag::PossessiveSingularNoun,
        "nns" => BrownTag::PluralNoun,
        "nns$" => BrownTag::PossessivePluralProperNoun,
        "np" => BrownTag::ProperNoun,
        "np$" => BrownTag::PossessiveProperNoun,
        "nps" => BrownTag::PluralProperNoun,
        "nps$" => BrownTag::PossessivePluralProperNoun,
        "nr" => BrownTag::AdverbialNoun,
        "nrs" => BrownTag::PluralAdverbialNoun,
        "od" => BrownTag::OrdinalNumeral,
        "pn" => BrownTag::NominalPronoun,
        "pn$" => BrownTag::PossessiveNominalPronoun,
        "pp$" => BrownTag::PossessivePersonalPronoun,
        "pp$$" => BrownTag::SecondPossessivePronoun,
        "ppl" => BrownTag::SingularReflexivePersonalPronoun,
        "ppls" => BrownTag::PluralReflexivePersonalPronoun,
        "ppo" => BrownTag::ObjectivePersonalPronoun,
        "pps" => BrownTag::SingularNominativePronoun,
        "ppss" => BrownTag::OtherNominativePersonalPronoun,
        "ql" => BrownTag::Qualifier,
        "qlp" => BrownTag::PostQualifier,
        "rb" => BrownTag::Adverb,
        "rbr" => BrownTag::ComparativeAdverb,
        "rbt" => BrownTag::SuperlativeAdverb,
        "rn" => BrownTag::NominalAdverb,
        "rp" => BrownTag::AdverbParticle,
        "tl" => BrownTag::WordInTitle,
        "to" => BrownTag::InfinitiveMarker,
        "uh" => BrownTag::Interjection,
        "vb" => BrownTag::VerbBaseForm,
        "vbd" => BrownTag::VerbPastTense,
        "vbg" => BrownTag::VerbPresentParticiple,
        "vbn" => BrownTag::VerbPastPariciple,
        "vbz" => BrownTag::VerbThirdSingularPresent,
        "wdt" => BrownTag::DeterminerWH,
        "wp$" => BrownTag::PossessiveWHPronoun,
        "wpo" => BrownTag::ObjectiveWHPronoun,
        "wps" => BrownTag::NominativeWHPronoun,
        "wql" => BrownTag::QualifierWH,
        "wrb" => BrownTag::AdverbWH,
        _ => BrownTag::None,
    };

    tags::<BrownTag>::TagPair{word: new_word, tag: new_tag}
}

pub enum BrownTag {
    SentenceCloser,
    LeftParen,
    RightParen,
    Not,
    Dash,
    Comma,
    Colon,
    PreQualifier,
    PreQuantifierN,
    PreQuantifierX,
    PostDeterminer,
    Article,
    Be,
    Were,
    Was,
    Being,
    Am,
    Been,
    Are,
    Is,
    CoordinatingConjunction,
    CardinalNumeral,
    SubordinatingConjunction,
    Do,
    Did,
    Does,
    SingularDeterminer,
    DeterminerQualifier,
    PluralDeterminer,
    DoubleConjunction,
    Existential,
    ForeignWord,
    WordInHeadline,
    Have,
    HadPast,
    Having,
    HadPastParticiple,
    Has,
    Preposition,
    Adjective,
    ComparativeAdjective,
    SemSuperlativeAdjective,
    MorphSuperlativeAdjective,
    ModalAuxiliary,
    Cited,
    Noun,
    PossessiveSingularNoun,
    PluralNoun,
    PossessivePluralNoun,
    ProperNoun,
    PossessiveProperNoun,
    PluralProperNoun,
    PossessivePluralProperNoun,
    AdverbialNoun,
    PluralAdverbialNoun,
    OrdinalNumeral,
    NominalPronoun,
    PossessiveNominalPronoun,
    PossessivePersonalPronoun,
    SecondPossessivePronoun,
    SingularReflexivePersonalPronoun,
    PluralReflexivePersonalPronoun,
    ObjectivePersonalPronoun,
    SingularNominativePronoun,
    OtherNominativePersonalPronoun,
    Qualifier,
    PostQualifier,
    Adverb,
    ComparativeAdverb,
    SuperlativeAdverb,
    NominalAdverb,
    AdverbParticle,
    WordInTitle,
    InfinitiveMarker,
    Interjection,
    VerbBaseForm,
    VerbPastTense,
    VerbPresentParticiple,
    VerbPastPariciple,
    VerbThirdSingularPresent,
    DeterminerWH,
    PossessiveWHPronoun,
    ObjectiveWHPronoun,
    NominativeWHPronoun,
    QualifierWH,
    AdverbWH,
    None,
}

pub struct BrownProbability {
    SentenceCloser: f32,
    LeftParen: f32,
    RightParen: f32,
    Not: f32,
    Dash: f32,
    Comma: f32,
    Colon: f32,
    PreQualifier: f32,
    PreQuantifierN: f32,
    PreQuantifierX: f32,
    PostDeterminer: f32,
    Article: f32,
    Be: f32,
    Were: f32,
    Was: f32,
    Being: f32,
    Am: f32,
    Been: f32,
    Are: f32,
    Is: f32,
    CoordinatingConjunction: f32,
    CardinalNumeral: f32,
    SubordinatingConjunction: f32,
    Do: f32,
    Did: f32,
    Does: f32,
    SingularDeterminer: f32,
    DeterminerQualifier: f32,
    PluralDeterminer: f32,
    DoubleConjunction: f32,
    Existential: f32,
    ForeignWord: f32,
    WordInHeadline: f32,
    Have: f32,
    HadPast: f32,
    Having: f32,
    HadPastParticiple: f32,
    Has: f32,
    Preposition: f32,
    Adjective: f32,
    ComparativeAdjective: f32,
    SemSuperlativeAdjective: f32,
    MorphSuperlativeAdjective: f32,
    ModalAuxiliary: f32,
    Cited: f32,
    Noun: f32,
    PossessiveSingularNoun: f32,
    PluralNoun: f32,
    PossessivePluralNoun: f32,
    ProperNoun: f32,
    PossessiveProperNoun: f32,
    PluralProperNoun: f32,
    PossessivePluralProperNoun: f32,
    AdverbialNoun: f32,
    PluralAdverbialNoun: f32,
    OrdinalNumeral: f32,
    NominalPronoun: f32,
    PossessiveNominalPronoun: f32,
    PossessivePersonalPronoun: f32,
    SecondPossessivePronoun: f32,
    SingularReflexivePersonalPronoun: f32,
    PluralReflexivePersonalPronoun: f32,
    ObjectivePersonalPronoun: f32,
    SingularNominativePronoun: f32,
    OtherNominativePersonalPronoun: f32,
    Qualifier: f32,
    PostQualifier: f32,
    Adverb: f32,
    ComparativeAdverb: f32,
    SuperlativeAdverb: f32,
    NominalAdverb: f32,
    AdverbParticle: f32,
    WordInTitle: f32,
    InfinitiveMarker: f32,
    Interjection: f32,
    VerbBaseForm: f32,
    VerbPastTense: f32,
    VerbPresentParticiple: f32,
    VerbPastPariciple: f32,
    VerbThirdSingularPresent: f32,
    DeterminerWH: f32,
    PossessiveWHPronoun: f32,
    ObjectiveWHPronoun: f32,
    NominativeWHPronoun: f32,
    QualifierWH: f32,
    AdverbWH: f32,
}

struct BrownIntermediaryProbability {
    SentenceCloser: BrownProbability,
    LeftParen: BrownProbability,
    RightParen: BrownProbability,
    Not: BrownProbability,
    Dash: BrownProbability,
    Comma: BrownProbability,
    Colon: BrownProbability,
    PreQualifier: BrownProbability,
    PreQuantifierN: BrownProbability,
    PreQuantifierX: BrownProbability,
    PostDeterminer: BrownProbability,
    Article: BrownProbability,
    Be: BrownProbability,
    Were: BrownProbability,
    Was: BrownProbability,
    Being: BrownProbability,
    Am: BrownProbability,
    Been: BrownProbability,
    Are: BrownProbability,
    Is: BrownProbability,
    CoordinatingConjunction: BrownProbability,
    CardinalNumeral: BrownProbability,
    SubordinatingConjunction: BrownProbability,
    Do: BrownProbability,
    Did: BrownProbability,
    Does: BrownProbability,
    SingularDeterminer: BrownProbability,
    DeterminerQualifier: BrownProbability,
    PluralDeterminer: BrownProbability,
    DoubleConjunction: BrownProbability,
    Existential: BrownProbability,
    ForeignWord: BrownProbability,
    WordInHeadline: BrownProbability,
    Have: BrownProbability,
    HadPast: BrownProbability,
    Having: BrownProbability,
    HadPastParticiple: BrownProbability,
    Has: BrownProbability,
    Preposition: BrownProbability,
    Adjective: BrownProbability,
    ComparativeAdjective: BrownProbability,
    SemSuperlativeAdjective: BrownProbability,
    MorphSuperlativeAdjective: BrownProbability,
    ModalAuxiliary: BrownProbability,
    Cited: BrownProbability,
    Noun: BrownProbability,
    PossessiveSingularNoun: BrownProbability,
    PluralNoun: BrownProbability,
    PossessivePluralNoun: BrownProbability,
    ProperNoun: BrownProbability,
    PossessiveProperNoun: BrownProbability,
    PluralProperNoun: BrownProbability,
    PossessivePluralProperNoun: BrownProbability,
    AdverbialNoun: BrownProbability,
    PluralAdverbialNoun: BrownProbability,
    OrdinalNumeral: BrownProbability,
    NominalPronoun: BrownProbability,
    PossessiveNominalPronoun: BrownProbability,
    PossessivePersonalPronoun: BrownProbability,
    SecondPossessivePronoun: BrownProbability,
    SingularReflexivePersonalPronoun: BrownProbability,
    PluralReflexivePersonalPronoun: BrownProbability,
    ObjectivePersonalPronoun: BrownProbability,
    SingularNominativePronoun: BrownProbability,
    OtherNominativePersonalPronoun: BrownProbability,
    Qualifier: BrownProbability,
    PostQualifier: BrownProbability,
    Adverb: BrownProbability,
    ComparativeAdverb: BrownProbability,
    SuperlativeAdverb: BrownProbability,
    NominalAdverb: BrownProbability,
    AdverbParticle: BrownProbability,
    WordInTitle: BrownProbability,
    InfinitiveMarker: BrownProbability,
    Interjection: BrownProbability,
    VerbBaseForm: BrownProbability,
    VerbPastTense: BrownProbability,
    VerbPresentParticiple: BrownProbability,
    VerbPastPariciple: BrownProbability,
    VerbThirdSingularPresent: BrownProbability,
    DeterminerWH: BrownProbability,
    PossessiveWHPronoun: BrownProbability,
    ObjectiveWHPronoun: BrownProbability,
    NominativeWHPronoun: BrownProbability,
    QualifierWH: BrownProbability,
    AdverbWH: BrownProbability,
}

pub struct BrownTagProbability {
    SentenceCloser: BrownIntermediaryProbability,
    LeftParen: BrownIntermediaryProbability,
    RightParen: BrownIntermediaryProbability,
    Not: BrownIntermediaryProbability,
    Dash: BrownIntermediaryProbability,
    Comma: BrownIntermediaryProbability,
    Colon: BrownIntermediaryProbability,
    PreQualifier: BrownIntermediaryProbability,
    PreQuantifierN: BrownIntermediaryProbability,
    PreQuantifierX: BrownIntermediaryProbability,
    PostDeterminer: BrownIntermediaryProbability,
    Article: BrownIntermediaryProbability,
    Be: BrownIntermediaryProbability,
    Were: BrownIntermediaryProbability,
    Was: BrownIntermediaryProbability,
    Being: BrownIntermediaryProbability,
    Am: BrownIntermediaryProbability,
    Been: BrownIntermediaryProbability,
    Are: BrownIntermediaryProbability,
    Is: BrownIntermediaryProbability,
    CoordinatingConjunction: BrownIntermediaryProbability,
    CardinalNumeral: BrownIntermediaryProbability,
    SubordinatingConjunction: BrownIntermediaryProbability,
    Do: BrownIntermediaryProbability,
    Did: BrownIntermediaryProbability,
    Does: BrownIntermediaryProbability,
    SingularDeterminer: BrownIntermediaryProbability,
    DeterminerQualifier: BrownIntermediaryProbability,
    PluralDeterminer: BrownIntermediaryProbability,
    DoubleConjunction: BrownIntermediaryProbability,
    Existential: BrownIntermediaryProbability,
    ForeignWord: BrownIntermediaryProbability,
    WordInHeadline: BrownIntermediaryProbability,
    Have: BrownIntermediaryProbability,
    HadPast: BrownIntermediaryProbability,
    Having: BrownIntermediaryProbability,
    HadPastParticiple: BrownIntermediaryProbability,
    Has: BrownIntermediaryProbability,
    Preposition: BrownIntermediaryProbability,
    Adjective: BrownIntermediaryProbability,
    ComparativeAdjective: BrownIntermediaryProbability,
    SemSuperlativeAdjective: BrownIntermediaryProbability,
    MorphSuperlativeAdjective: BrownIntermediaryProbability,
    ModalAuxiliary: BrownIntermediaryProbability,
    Cited: BrownIntermediaryProbability,
    Noun: BrownIntermediaryProbability,
    PossessiveSingularNoun: BrownIntermediaryProbability,
    PluralNoun: BrownIntermediaryProbability,
    PossessivePluralNoun: BrownIntermediaryProbability,
    ProperNoun: BrownIntermediaryProbability,
    PossessiveProperNoun: BrownIntermediaryProbability,
    PluralProperNoun: BrownIntermediaryProbability,
    PossessivePluralProperNoun: BrownIntermediaryProbability,
    AdverbialNoun: BrownIntermediaryProbability,
    PluralAdverbialNoun: BrownIntermediaryProbability,
    OrdinalNumeral: BrownIntermediaryProbability,
    NominalPronoun: BrownIntermediaryProbability,
    PossessiveNominalPronoun: BrownIntermediaryProbability,
    PossessivePersonalPronoun: BrownIntermediaryProbability,
    SecondPossessivePronoun: BrownIntermediaryProbability,
    SingularReflexivePersonalPronoun: BrownIntermediaryProbability,
    PluralReflexivePersonalPronoun: BrownIntermediaryProbability,
    ObjectivePersonalPronoun: BrownIntermediaryProbability,
    SingularNominativePronoun: BrownIntermediaryProbability,
    OtherNominativePersonalPronoun: BrownIntermediaryProbability,
    Qualifier: BrownIntermediaryProbability,
    PostQualifier: BrownIntermediaryProbability,
    Adverb: BrownIntermediaryProbability,
    ComparativeAdverb: BrownIntermediaryProbability,
    SuperlativeAdverb: BrownIntermediaryProbability,
    NominalAdverb: BrownIntermediaryProbability,
    AdverbParticle: BrownIntermediaryProbability,
    WordInTitle: BrownIntermediaryProbability,
    InfinitiveMarker: BrownIntermediaryProbability,
    Interjection: BrownIntermediaryProbability,
    VerbBaseForm: BrownIntermediaryProbability,
    VerbPastTense: BrownIntermediaryProbability,
    VerbPresentParticiple: BrownIntermediaryProbability,
    VerbPastPariciple: BrownIntermediaryProbability,
    VerbThirdSingularPresent: BrownIntermediaryProbability,
    DeterminerWH: BrownIntermediaryProbability,
    PossessiveWHPronoun: BrownIntermediaryProbability,
    ObjectiveWHPronoun: BrownIntermediaryProbability,
    NominativeWHPronoun: BrownIntermediaryProbability,
    QualifierWH: BrownIntermediaryProbability,
    AdverbWH: BrownIntermediaryProbability,
}
